<?php

namespace App\Http\Models;

use Corcel\Model\Post as Corcel;
use Illuminate\Database\Eloquent\Builder;

class Product extends Corcel
{
    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('post_type', function (Builder $builder) {
            $builder->where('post_type', '=', 'product');
        });
    }
}
